version: "3.3"
services:
  dummy-cf-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dummy-cf-proxy
    ports:
      - "2080:80"
    environment:
      - TZ=Asia/Tokyo
      - RESOLVER=127.0.0.11 ipv6=off
      - FORCE_SECURE=false
    networks:
      - ats_default
networks:
  ats_default:
    external: true
